import {
    BaseEntityViewCompCustomSettingsSchema,
    DEFAULT_WIDGET_MAIN_SETTING_TABS,
    EntityCustomSettingParamType,
    EntityViewCustomSettingsParamType,
    DEFAULT_WIDGET_STYLE_SETTING_TABS,
    CUSTOM_SETTINGS_STYLE_PARAM,
    CUSTOM_SETTINGS_ENTITY_ID_PARAM,
    EntityViewCompCustomSettingsStructuredObjectParam,
    CUSTOM_SETTINGS_UNIT_PARAM_GROUP,
    CUSTOM_SETTINGS_DECIMAL_PARAM_GROUP,
    EntityViewCompCustomSettingsParamGroup,
    CUSTOM_SETTINGS_GLOBAL_NUMERIC_METRICS_VIEW_SETTINGS_PARAM,
    CUSTOM_SETTINGS_DATA_SOURCE_CUSTOM_DATA_SOURCE_CONFIGURATION_PARAM,
    CUSTOM_SETTINGS_DATA_SOURCE_METRICS_DEFINITION_ID_PARAM,
    CUSTOM_SETTINGS_METRICS_DATA_SOURCES_SETTINGS_PARAM,
    EntityViewCompCustomSettingsStructuredObjectArrayParam,
    CUSTOM_SETTINGS_DATA_SOURCE_NUMERIC_VALUE_RANGE_PARAM,
    CUSTOM_SETTINGS_DATA_SOURCE_NUMERIC_VALUE_DISABLE_RANGE_PARAM_GROUP,
    CUSTOM_SETTINGS_DATA_SOURCE_NUMERIC_METRIC_VALUE_NAME_PARAM,
    CUSTOM_SETTINGS_DATA_SOURCE_NUMERIC_METRICS_PARAM,
    CUSTOM_SETTINGS_DATA_SOURCE_NUMERIC_VALUE_HIDDEN_PARAM,
    CUSTOM_SETTINGS_DATA_SOURCE_NUMERIC_VALUE_TRANSFORMATION_FORMULA_PARAM,
    CUSTOM_SETTINGS_DATA_SOURCE_VIEW_SETTINGS_DISPLAY_NAME_PARAM,
    CUSTOM_SETTINGS_DATA_SOURCE_NUMERIC_METRIC_VIEW_SETTINGS_PARAM,
    CHART_CUSTOM_SETTINGS_SERIES_STYLE_PARAM,
    CHART_TYPE_PARAM,
    CUSTOM_SETTINGS_DATA_SOURCE_TARGET_ENTITY_CLASS_PARAM,
    CUSTOM_SETTINGS_DATA_SOURCE_ENTITY_ID_PARAM,
    CUSTOM_SETTINGS_DATA_SOURCE_TARGET_ENTITY_CLASS_SETTINGS_PARAMS,
    CUSTOM_SETTINGS_DATA_SOURCE_AGGREGATION_PARAM,
    CUSTOM_SETTINGS_DATA_SOURCE_RESOLUTION_PARAM,
    CHART_GLOBAL_VIEW_SETTINGS_PARAM,
    CHART_CUSTOM_SETTINGS_DATA_LABEL_TEMPLATE_PARAM,
    CHART_CUSTOM_SETTINGS_TARGET_RANGE_PARAM,
    CUSTOM_SETTINGS_DATA_SOURCE_NUMERIC_VALUE_GROUP_NAME_PARAM,
    CUSTOM_SETTINGS_CUSTOM_TIME_CONTROL_PARAM,
    CUSTOM_SETTINGS_CONTAINER_SETTINGS_PARAM,
} from '@moderepo/bizstack-console-sdk';

// A copy of CUSTOM_SETTINGS_DATA_SOURCE_NUMERIC_METRIC_VIEW_SETTINGS_PARAM but with additional params for XY Chart
const XY_CHART_CUSTOM_SETTINGS_DATA_SOURCE_NUMERIC_METRIC_VIEW_SETTINGS_PARAM = {
    ...CUSTOM_SETTINGS_DATA_SOURCE_NUMERIC_METRIC_VIEW_SETTINGS_PARAM,
    params: [
        {
            paramType: EntityViewCustomSettingsParamType.PARAM_GROUP,
            name: 'group1',
            label: '',
            viewSettings: {
                paramsPerRow: 2,
                condensed: true,
                hideHeader: true,
            },
            params: [CHART_TYPE_PARAM, CUSTOM_SETTINGS_DATA_SOURCE_VIEW_SETTINGS_DISPLAY_NAME_PARAM],
        } satisfies EntityViewCompCustomSettingsParamGroup,
        CUSTOM_SETTINGS_UNIT_PARAM_GROUP,
        CUSTOM_SETTINGS_DECIMAL_PARAM_GROUP,
        CUSTOM_SETTINGS_DATA_SOURCE_NUMERIC_VALUE_RANGE_PARAM,
        CUSTOM_SETTINGS_DATA_SOURCE_NUMERIC_VALUE_DISABLE_RANGE_PARAM_GROUP,
        CUSTOM_SETTINGS_DATA_SOURCE_NUMERIC_VALUE_TRANSFORMATION_FORMULA_PARAM,
        CHART_CUSTOM_SETTINGS_DATA_LABEL_TEMPLATE_PARAM,
        CHART_CUSTOM_SETTINGS_TARGET_RANGE_PARAM,
        CHART_CUSTOM_SETTINGS_SERIES_STYLE_PARAM,
        CUSTOM_SETTINGS_DATA_SOURCE_NUMERIC_VALUE_GROUP_NAME_PARAM,
        CUSTOM_SETTINGS_DATA_SOURCE_NUMERIC_VALUE_HIDDEN_PARAM,
    ],
};

// A copy of CUSTOM_SETTINGS_DATA_SOURCE_NUMERIC_METRICS_PARAM but with additional params for XY Chart
const XY_CHART_CUSTOM_SETTINGS_DATA_SOURCE_NUMERIC_METRICS_PARAM: EntityViewCompCustomSettingsStructuredObjectArrayParam = {
    ...CUSTOM_SETTINGS_DATA_SOURCE_NUMERIC_METRICS_PARAM,
    params: [CUSTOM_SETTINGS_DATA_SOURCE_NUMERIC_METRIC_VALUE_NAME_PARAM, XY_CHART_CUSTOM_SETTINGS_DATA_SOURCE_NUMERIC_METRIC_VIEW_SETTINGS_PARAM],
};

// A copy of CUSTOM_SETTINGS_DATA_SOURCES_SETTINGS_PARAM but with additional params for XY Chart
const XY_CHART_CUSTOM_SETTINGS_DATA_SOURCES_SETTINGS_PARAM: EntityViewCompCustomSettingsStructuredObjectArrayParam = {
    ...CUSTOM_SETTINGS_METRICS_DATA_SOURCES_SETTINGS_PARAM,
    params: [
        CUSTOM_SETTINGS_DATA_SOURCE_TARGET_ENTITY_CLASS_PARAM,
        CUSTOM_SETTINGS_DATA_SOURCE_ENTITY_ID_PARAM,
        CUSTOM_SETTINGS_DATA_SOURCE_TARGET_ENTITY_CLASS_SETTINGS_PARAMS,
        CUSTOM_SETTINGS_DATA_SOURCE_METRICS_DEFINITION_ID_PARAM,
        CUSTOM_SETTINGS_DATA_SOURCE_CUSTOM_DATA_SOURCE_CONFIGURATION_PARAM,
        XY_CHART_CUSTOM_SETTINGS_DATA_SOURCE_NUMERIC_METRICS_PARAM,
        CUSTOM_SETTINGS_DATA_SOURCE_AGGREGATION_PARAM,
        CUSTOM_SETTINGS_DATA_SOURCE_RESOLUTION_PARAM,
    ],
};

// A copy of CUSTOM_SETTINGS_GLOBAL_NUMERIC_METRIC_VIEW_SETTINGS_PARAM but with additional params for XY Chart
const XY_CHART_CUSTOM_SETTINGS_GLOBAL_NUMERIC_METRIC_VIEW_SETTINGS_PARAM: EntityViewCompCustomSettingsStructuredObjectParam = {
    ...CUSTOM_SETTINGS_GLOBAL_NUMERIC_METRICS_VIEW_SETTINGS_PARAM,
    params: [
        CHART_TYPE_PARAM,
        CUSTOM_SETTINGS_UNIT_PARAM_GROUP,
        CUSTOM_SETTINGS_DECIMAL_PARAM_GROUP,
        CUSTOM_SETTINGS_DATA_SOURCE_NUMERIC_VALUE_RANGE_PARAM,
        CUSTOM_SETTINGS_DATA_SOURCE_NUMERIC_VALUE_DISABLE_RANGE_PARAM_GROUP,
        CHART_CUSTOM_SETTINGS_SERIES_STYLE_PARAM,
    ],
};

/**
 * Create the Schema for the XYChartWidgetCustomSettings so that it can be configured from a UI
 */
export const xyChartWidgetCustomSettingsSchema: BaseEntityViewCompCustomSettingsSchema = {
    tabs: [
        {
            ...DEFAULT_WIDGET_MAIN_SETTING_TABS,
            params: [
                CUSTOM_SETTINGS_ENTITY_ID_PARAM,
                {
                    // xyChartChartTypeParam is a param of style settings, but for convenience, expose the param here as well.
                    paramType: EntityViewCustomSettingsParamType.PARAM,
                    type: EntityCustomSettingParamType.STRUCTURED_OBJECT,
                    key: 'globalNumericMetricsViewSettings',
                    required: false,
                    label: '{{entity.view_comp.common.custom_settings.global_custom_view_settings.label}}',
                    description: '{{entity.view_comp.common.custom_settings.global_custom_view_settings.description}}',
                    params: [CHART_TYPE_PARAM],
                },
                XY_CHART_CUSTOM_SETTINGS_DATA_SOURCES_SETTINGS_PARAM,
                CUSTOM_SETTINGS_CUSTOM_TIME_CONTROL_PARAM,
            ],
        },
        {
            ...DEFAULT_WIDGET_STYLE_SETTING_TABS,
            params: [
                CUSTOM_SETTINGS_CONTAINER_SETTINGS_PARAM,
                XY_CHART_CUSTOM_SETTINGS_GLOBAL_NUMERIC_METRIC_VIEW_SETTINGS_PARAM,
                CHART_GLOBAL_VIEW_SETTINGS_PARAM,
                { ...CUSTOM_SETTINGS_STYLE_PARAM, isAdvancedSettings: true },
            ],
        },
    ],
};
